### PR TITLE
Add two week schedule

### PR DESCRIPTION
**Pull request by IsaacHatton**
Hi,

Here's some code I wrote to make two week schedule work in the webapp.
image

It does have a few issues that I can't resolve:

- Untested with single week timetable users (There's no reason why it wouldn't work, they would still have the week tab bar though)
- If the screen size is small, and the schedule is bigger than the viewport, the user can scroll horisontally, but the tab bar isn't wider so it it just blank space (sorry I know that's not worded very well, here's a screenshot)
- I was unsure what code style conventions to follow or tools to use (prettier etc), apologies if the code is inconsistent with the style of the rest of the codebase

image

### CODE REVIEW

**Comment by IsaacHatton** [comment]
@andrewleader Do you want me to create a matching issue for this

**Comment by andrewleader** [comment]
Oh wow I totally missed this! Pretty neat @IsaacHatton! I often miss my GitHub notifications, the best way to contact me is through the support email within Power Planner (and then I can share my direct email).

I know this is a year later, but if you're still interested in finishing this up I'd be willing to merge it. Seems like there's some bugs as you mentioned though. I think making the toolbar for switching weeks disappear if users don't have any items that are only Week A/Week B would be ideal. Otherwise I'm not too worried about the horizontal scrolling issue.

**Comment by IsaacHatton** [comment]
Hi @andrewleader ,
Thanks for getting back to me, I will take another look at fixing those issues in the next few days.

**Review by andrewleader — APPROVED** [review]
I figured out (and updated) the horizontal scrolling! Just had to make the root container a flexbox, and then have the schedulecontainer fill the remaining height. I pushed those tiny changes.

Everything else looks good! I tested on multiple of my accounts with and without two weeks, and across multiple sizes/heights of schedules. It looks good to me. I'm going to merge it!

**Pull request merged**
